DDF-3364 Fix the security-sts-server to successfully start up after restarting DDF when the broker-app is installed (#2493)
-Copies classes directly from the cxf-rt-ws-securityand wss4j bundles that depend on classes from the net.sf.ehcache package into DDF's security-sts-server bundle. There seemed to be a timing issue where the ehcache dependency brought in by cxf-rt-ws-security and wss4j wasn’t available at the time security-sts-server needed it, causing NoClassDefFoundError exceptions to occur. This fix will prevent the need for cxf-rt-ws-security and wss4j to bring in the ehcache dependency as the classes that depend on ehcache are contained in security-sts-server instead.